export const studyLevels = ['undergraduate', 'masters', 'foundation', 'top_up', 'phd', 'doctorate'];

export const subjects = [
    'accounting',
    'accounting & finance',
    'agriculture & forestry',
    'animal science',
    'anthropology',
    'archaeology',
    'architecture',
    'art, performing arts & design',
    'arts',
    'biological sciences',
    'biology',
    'bsc occupational therapy',
    'building',
    'business & management',
    'business studies',
    'chemical engineering',
    'chemistry',
    'chemistry / biochemistry',
    'cinematic and photography',
    'civil engineering',
    'communication & media studies',
    'communication and information science',
    'computer science',
    'culinary arts',
    'dentistry',
    'design studies',
    'development studies',
    'drama',
    'earth & marine sciences',
    'economics',
    'economics & econometrics',
    'education',
    'education studies',
    'electrical & electronic engineering',
    'engineering',
    'english studies',
    'environmental',
    'fashion',
    'finance',
    'general engineering',
    'geography',
    'geography: environmental science',
    'geology',
    'geology, environmental, earth & marine sciences',
    'health studies',
    'history',
    'history, philosophy & theology',
    'hr management',
    'journalism',
    'landscape design',
    'languages, literature & linguistics',
    'law',
    'linguistics',
    'literary studies',
    'management studies',
    'marketing',
    'materials science',
    'math',
    'mathematics & statistics',
    'mba',
    'mechanical & aerospace engineering',
    'media studies',
    'medicine',
    'medicine & dentistry',
    'modern languages and european studies',
    'msc occupational therapy (pre-reg)',
    'music',
    'not decided',
    'not set',
    'nursing',
    'nutrition',
    'other health',
    'pharmacology, toxicology & pharmacy',
    'photography',
    'physics',
    'physics & astronomy',
    'physiotherapy',
    'planning (urban, rural & regional)',
    'politics',
    'politics & international studies (incl development studies)',
    'psychology',
    'social policy',
    'social work',
    'sociology',
    'software engineering',
    'sport science',
    'tourism, transport & travel',
    'translation',
    'veterinary',
    'veterinary science',
    'other',
];

export const country_of_residence = [
    { country_name: 'bangladesh', code: '+880' },
    { country_name: 'uk', code: '+44' },
    { country_name: 'india', code: '+91' },
    { country_name: 'pakistan', code: '+92' },
    { country_name: 'sri-lanka', code: '+94' },
    { country_name: 'nepal', code: '+977' },
    { country_name: 'nigeria', code: '+234' },
    { country_name: 'saudi', code: '+966' },
    { country_name: 'uae', code: '+971' },
];
